version: 2.0

jobs:
    build:
        docker:
            - image: circleci/python
        steps:
            - checkout
            - add_ssh_keys:
                fingerprints:
                    - "a1:c7:35:0b:fc:48:19:98:3e:2d:44:08:dd:32:b1:60"
            - restore_cache:
                key: cache-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            - run: pipenv install --dev
            - save_cache:
                key: cache-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
                paths:
                    - "/home/circleci/.local/share/virtualenvs"
            - run: pipenv run build
            - run: sudo apt install rsync --yes
            - deploy:
                name: Deploy to Github Pages
                command: ./.circleci/deploy.sh
